name: tests

on: [push, pull_request]

jobs:
  cs-fix:
    name: PHP CS Fixer on PHP ${{ matrix.php }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.1']
      max-parallel: 20
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, pdo, pdo_mysql, bcmath, swoole
          tools: phpize
          coverage: none
      - name: Setup Packages
        run: composer update -o
      - name: Run Cs Fixer
        run: vendor/bin/php-cs-fixer fix $1 --dry-run --diff --verbose
  ci:
    needs: cs-fix
    name: Test on PHP ${{ matrix.php }} with Swoole ${{ matrix.swoole }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.3','8.2', '8.1']
        swoole: ['5.1.5', '6.0.0']
      max-parallel: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpize, pecl
          extensions: redis, swoole-${{ matrix.swoole }}
          coverage: none
      - name: Show PHP Information
        run: |
          php -v
          php --ri swoole
      - name: Setup Packages
        run: composer update -o
      - name: Run Analyse
        run: composer analyse src
      - name: Run Test Cases
        run: |
          cp phpunit.xml.dist phpunit.xml
          composer test